resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: Newtest
      path: HariAryal/newjfrog
      branches:
        include: main
        
pipelines:
  - name: pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: alina-dangol-qualiti-test
          dockerImageTag: ${run_number}
          inputResources:
            - name: myFirstRepo
          
